version: '3'
services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    depends_on:
      - db
    env_file: .env
    volumes:
      - ./www:/var/www/html
      - ./config/vhost.apache2.conf:/etc/apache2/sites-available/000-default.conf
    restart: unless-stopped
    environment:
      DB_HOST: ${DB_NAME}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_USER}
      DOMAIN: ${DOMAIN}
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
      - "${VITE_PORT}:12321"
  db:
    image: mariadb:10.8
    volumes:
      - "db_data:/var/lib/mysql"
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:3306"
volumes:
  db_data: