version: '3'
networks:
  traefik:
    name: traefik
  backend:
volumes:
  db_data:
services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GID: ${GID:-1000}
        UID: ${UID:-1000}
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_NAME}
      DB_NAME: ${DB_NAME}
      DB_PASS: ${DB_USER}
      DB_USER: ${DB_USER}
      DOMAIN: ${DOMAIN}
    env_file: .env
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - backend
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}-drupal.entrypoints=web"
      - "traefik.http.routers.${PROJECT_NAME}-drupal.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}-drupal.service=${PROJECT_NAME}-drupal"
      - "traefik.http.services.${PROJECT_NAME}-drupal.loadbalancer.server.port=80"
    ports:
      - "${VITE_PORT:-12321}:${VITE_PORT:-12321}"
    restart: unless-stopped
    volumes:
      - ./www:/var/www/html
      - ./config/vhost.apache2.conf:/etc/apache2/sites-available/000-default.conf
  db:
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      MARIADB_USER: ${DB_USER}
    image: mariadb:10.8
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - "db_data:/var/lib/mysql"
  traefik:
    command:
      - "--api.insecure=true"
      - "--entrypoints.dba.address=:81"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
    image: traefik:2.8
    networks:
      - traefik
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
      - "${DB_PORT}:81"
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"