<?php

/**
 * @file
 * Primary module hooks for Cookie notice module.
 */

/**
 * Implements hook_theme().
 */
function cookie_notice_theme($existing, $type, $theme, $path) {
  return [
    'block__cookie_notice__cookie_notice' => [
      'variables' => [
        'cookie_notice' => '',
        'hashed_notice' => '',
      ]
    ]
  ];
}

/**
 * Implements hook_preprocess_block().
 */
function cookie_notice_preprocess_block(&$variables) {
  if ($variables['plugin_id'] == 'cookie_notice') {
    $variables['#attached']['drupalSettings']['cookieNotice']['hashedValue'] = $variables['content']['#hashed_value'];
  }
}
