name: Build pipeline

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          export DOCKER_BUILDKIT=1
          cp .env.example .env
          docker compose build