name: Deploy pipeline

on:
  pull_request:
    branches:
      - 'main'
    types: 
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app on production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd domains/visualize
            git pull
            docker compose build
            docker exec -t visualize-drupal-1 composer install
            docker exec -t visualize-drupal-1 drush cim
            docker exec -t visualize-drupal-1 drush cr
            docker exec -t visualize-drupal-1 npm run build
