name: Deploy pipeline

on:
  pull_request:
    branches:
      - 'main'
    types: 
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app on production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd domains/visualize && git pull
            docker compose build
            docker exec -t visualize-drupal-1 composer install --no-cache
            docker exec -t visualize-drupal-1 drush -y cim && drush cr
            docker exec -t visualize-drupal-1 yarn && yarn build && rm -rf node_modules
