name: Build pipeline

on:
  pull_request:
    branches:
      - "main"
    types:
      - closed
jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd domains/visualize
            git pull --ff-only origin main
            docker compose build
            make prod
