name: Visualize pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  DOMAIN: ${{ secrets.DOMAIN }}
  # database config
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASS }}
  # ports config
  DB_PORT: ${{ secrets.DB_PORT }}
  HTTP_PORT: ${{ secrets.HTTP_PORT }}
  HTTPS_PORT: ${{ secrets.HTTPS_PORT }}
  PMA_PORT: ${{ secrets.PMA_PORT }}
  VITE_PORT: ${{ secrets.VITE_PORT }}
  # ubuntu image config
  UID: ${{ secrets.UID }}
  GID: ${{ secrets.GID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cp .env.example .env
        docker compose build
  run:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Run the Docker container
      run: |
        docker compose up -d
